# Type stubs for pcollections.
#
# The public types come from either the C backend or the pure-Python backend
# at import time; these stubs describe the interface that both provide.

from collections.abc import (
    Callable, Hashable, ItemsView, Iterable, Iterator, KeysView, Mapping,
    MutableMapping, MutableSequence, MutableSet, Sequence, Set, ValuesView)
from types import TracebackType
from typing import (
    Any, ClassVar, Generic, Literal, Protocol, SupportsIndex, TypeVar,
    overload)

from typing_extensions import Self, disjoint_base

_T = TypeVar("_T")
_S = TypeVar("_S")
_K = TypeVar("_K")
_V = TypeVar("_V")
_T_co = TypeVar("_T_co", covariant=True)
_V_co = TypeVar("_V_co", covariant=True)

__version__: str
using_c_extension: bool
backend_error: BaseException | None


class _SupportsKeysAndGetItem(Protocol[_K, _V_co]):
    def keys(self) -> Iterable[_K]: ...
    def __getitem__(self, key: _K, /) -> _V_co: ...


#-------------------------------------------------------------------------------
# Dictionaries

@disjoint_base
class pdict(Mapping[_K, _V], Hashable):
    """A persistent (immutable) dictionary."""
    __transient_type__: ClassVar[type[tdict[Any, Any]]]
    empty: ClassVar[pdict[Any, Any]]
    @overload
    def __new__(cls) -> Self: ...  # pyright: ignore[reportOverlappingOverload]
    @overload
    def __new__(cls, **kwargs: _V) -> pdict[str, _V]: ...
    @overload
    def __new__(cls, map: Mapping[_K, _V], /) -> Self: ...  # type: ignore[overload-overlap]
    @overload
    def __new__(cls, map: Mapping[str, _V], /,
                **kwargs: _V) -> pdict[str, _V]: ...
    @overload
    def __new__(cls, iterable: Iterable[tuple[_K, _V]], /) -> Self: ...
    @overload
    def __new__(cls,
                iterable: Iterable[tuple[str, _V]], /,
                **kwargs: _V) -> pdict[str, _V]: ...
    def __class_getitem__(cls, item: Any, /) -> Any: ...
    def __getitem__(self, key: _K, /) -> _V: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __reversed__(self) -> Iterator[_K]: ...
    def __or__(self, other: Mapping[_S, _T], /) -> pdict[_K | _S, _V | _T]: ...
    def __ror__(self, other: Mapping[_S, _T], /) -> pdict[_K | _S, _V | _T]: ...
    @classmethod
    @overload
    def fromkeys(cls, iterable: Iterable[_S], value: None = None
                 ) -> pdict[_S, Any | None]: ...
    @classmethod
    @overload
    def fromkeys(cls, iterable: Iterable[_S], value: _T) -> pdict[_S, _T]: ...
    def keys(self) -> KeysView[_K]: ...
    def values(self) -> ValuesView[_V]: ...
    def items(self) -> ItemsView[_K, _V]: ...
    @overload
    def get(self, key: _K, default: None = None, /) -> _V | None: ...
    @overload
    def get(self, key: _K, default: _V | _T, /) -> _V | _T: ...
    def transient(self) -> tdict[_K, _V]: ...
    def copy(self) -> Self: ...
    def clear(self) -> Self: ...
    def set(self, key: _K, val: _V, /) -> Self: ...
    def setall(self, keys: Iterable[_K], vals: Iterable[_V]) -> Self: ...
    def setdefault(self, key: _K, default: _V | None = None) -> Self: ...
    def update(self, *args: Any, **kwargs: _V) -> Self: ...
    def drop(self, key: _K, error: bool = False) -> Self: ...
    def dropall(self, keys: Iterable[_K]) -> Self: ...
    def delete(self, key: _K) -> Self: ...
    def deleteall(self, keys: Iterable[_K]) -> Self: ...
    @overload
    def pop(self, key: _K) -> tuple[_V, Self]: ...
    @overload
    def pop(self, key: _K, default: _V | _T) -> tuple[_V | _T, Self]: ...
    def popitem(self) -> tuple[tuple[_K, _V], Self]: ...


@disjoint_base
class tdict(MutableMapping[_K, _V]):
    """A transient (mutable) dictionary that can be efficiently converted to
    and from a `pdict`."""
    __persistent_type__: ClassVar[type[pdict[Any, Any]]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @overload
    def __new__(cls) -> Self: ...  # pyright: ignore[reportOverlappingOverload]
    @overload
    def __new__(cls, **kwargs: _V) -> tdict[str, _V]: ...
    @overload
    def __new__(cls, map: Mapping[_K, _V], /) -> Self: ...  # type: ignore[overload-overlap]
    @overload
    def __new__(cls, map: Mapping[str, _V], /,
                **kwargs: _V) -> tdict[str, _V]: ...
    @overload
    def __new__(cls, iterable: Iterable[tuple[_K, _V]], /) -> Self: ...
    @overload
    def __new__(cls,
                iterable: Iterable[tuple[str, _V]], /,
                **kwargs: _V) -> tdict[str, _V]: ...
    def __class_getitem__(cls, item: Any, /) -> Any: ...
    @classmethod
    def empty(cls) -> Self: ...
    def __getitem__(self, key: _K, /) -> _V: ...
    def __setitem__(self, key: _K, value: _V, /) -> None: ...
    def __delitem__(self, key: _K, /) -> None: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __len__(self) -> int: ...
    def __reversed__(self) -> Iterator[_K]: ...
    def __or__(self, other: Mapping[_S, _T], /) -> tdict[_K | _S, _V | _T]: ...
    def __ror__(self, other: Mapping[_S, _T], /) -> tdict[_K | _S, _V | _T]: ...
    @overload  # type: ignore[misc]
    def __ior__(self, other: _SupportsKeysAndGetItem[_K, _V], /) -> Self: ...
    @overload
    def __ior__(self, other: Iterable[tuple[_K, _V]], /) -> Self: ...
    @classmethod
    @overload
    def fromkeys(cls, iterable: Iterable[_S], value: None = None
                 ) -> tdict[_S, Any | None]: ...
    @classmethod
    @overload
    def fromkeys(cls, iterable: Iterable[_S], value: _T) -> tdict[_S, _T]: ...
    def keys(self) -> KeysView[_K]: ...
    def values(self) -> ValuesView[_V]: ...
    def items(self) -> ItemsView[_K, _V]: ...
    @overload
    def get(self, key: _K, default: None = None, /) -> _V | None: ...
    @overload
    def get(self, key: _K, default: _V | _T, /) -> _V | _T: ...
    def persistent(self) -> pdict[_K, _V]: ...
    def copy(self) -> Self: ...


#-------------------------------------------------------------------------------
# Lists

@disjoint_base
class plist(Sequence[_T], Hashable):
    """A persistent (immutable) list."""
    __transient_type__: ClassVar[type[tlist[Any]]]
    empty: ClassVar[plist[Any]]
    @overload
    def __new__(cls) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T], /) -> Self: ...
    def __class_getitem__(cls, item: Any, /) -> Any: ...
    @overload
    def __getitem__(self, index: SupportsIndex, /) -> _T: ...
    @overload
    def __getitem__(self, index: slice, /) -> Self: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __reversed__(self) -> Iterator[_T]: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: Sequence[_T], /) -> bool: ...
    def __le__(self, other: Sequence[_T], /) -> bool: ...
    def __gt__(self, other: Sequence[_T], /) -> bool: ...
    def __ge__(self, other: Sequence[_T], /) -> bool: ...
    def __add__(self, other: list[_S] | plist[_S] | tlist[_S], /
                ) -> plist[_T | _S]: ...
    def __radd__(self, other: list[_S], /) -> plist[_T | _S]: ...
    def __mul__(self, n: SupportsIndex, /) -> Self: ...
    def __rmul__(self, n: SupportsIndex, /) -> Self: ...
    def index(self, value: Any, start: SupportsIndex = 0,
              stop: SupportsIndex | None = None) -> int: ...
    def count(self, value: Any) -> int: ...
    def transient(self) -> tlist[_T]: ...
    def copy(self) -> Self: ...
    def clear(self) -> Self: ...
    def set(self, index: SupportsIndex, obj: _T, /) -> Self: ...
    def append(self, obj: _T, /) -> Self: ...
    def prepend(self, obj: _T, /) -> Self: ...
    def extend(self, iterable: Iterable[_T]) -> Self: ...
    def insert(self, index: SupportsIndex, obj: _T, /) -> Self: ...
    def drop(self, index: SupportsIndex = -1, error: bool = False) -> Self: ...
    def delete(self, index: SupportsIndex = -1, /) -> Self: ...
    def remove(self, value: Any) -> Self: ...
    def pop(self, index: SupportsIndex = -1) -> tuple[_T, Self]: ...
    def reverse(self) -> Self: ...
    def sort(self, key: Callable[[_T], Any] | None = None,
             reverse: bool = False) -> Self: ...


@disjoint_base
class tlist(MutableSequence[_T]):
    """A transient (mutable) list that can be efficiently converted to and
    from a `plist`."""
    __persistent_type__: ClassVar[type[plist[Any]]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @overload
    def __new__(cls) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T], /) -> Self: ...
    def __class_getitem__(cls, item: Any, /) -> Any: ...
    @classmethod
    def empty(cls) -> Self: ...
    @overload
    def __getitem__(self, index: SupportsIndex, /) -> _T: ...
    @overload
    def __getitem__(self, index: slice, /) -> Self: ...
    @overload
    def __setitem__(self, index: SupportsIndex, value: _T, /) -> None: ...
    @overload
    def __setitem__(self, index: slice, value: Iterable[_T], /) -> None: ...
    def __delitem__(self, index: SupportsIndex | slice, /) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __reversed__(self) -> Iterator[_T]: ...
    def __lt__(self, other: Sequence[_T], /) -> bool: ...
    def __le__(self, other: Sequence[_T], /) -> bool: ...
    def __gt__(self, other: Sequence[_T], /) -> bool: ...
    def __ge__(self, other: Sequence[_T], /) -> bool: ...
    def __add__(self, other: list[_S] | plist[_S] | tlist[_S], /
                ) -> tlist[_T | _S]: ...
    def __radd__(self, other: list[_S], /) -> tlist[_T | _S]: ...
    def __iadd__(self, other: Iterable[_T], /) -> Self: ...  # type: ignore[misc]
    def __mul__(self, n: SupportsIndex, /) -> Self: ...
    def __rmul__(self, n: SupportsIndex, /) -> Self: ...
    def __imul__(self, n: SupportsIndex, /) -> Self: ...
    def append(self, obj: _T, /) -> None: ...
    def insert(self, index: SupportsIndex, obj: _T, /) -> None: ...
    def prepend(self, obj: _T, /) -> None: ...
    def index(self, value: Any, start: SupportsIndex = 0,
              stop: SupportsIndex | None = None) -> int: ...
    def count(self, value: Any) -> int: ...
    def pop(self, index: SupportsIndex = -1, /) -> _T: ...
    def sort(self, key: Callable[[_T], Any] | None = None,
             reverse: bool = False) -> None: ...
    def persistent(self) -> plist[_T]: ...
    def copy(self) -> Self: ...


#-------------------------------------------------------------------------------
# Sets

@disjoint_base
class pset(Set[_T_co], Hashable):
    """A persistent (immutable) set. A `pset` has the same hash as an equal
    `frozenset`."""
    __transient_type__: ClassVar[type[tset[Any]]]
    empty: ClassVar[pset[Any]]
    @overload
    def __new__(cls) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T_co], /) -> Self: ...
    def __class_getitem__(cls, item: Any, /) -> Any: ...
    def __contains__(self, obj: object, /) -> bool: ...
    def __iter__(self) -> Iterator[_T_co]: ...
    def __len__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __or__(self, other: Set[_S], /) -> pset[_T_co | _S]: ...
    def __ror__(self, other: Set[_S], /) -> pset[_T_co | _S]: ...  # type: ignore[misc]
    def __and__(self, other: Set[object], /) -> Self: ...
    def __sub__(self, other: Set[Any], /) -> Self: ...
    def __xor__(self, other: Set[_S], /) -> pset[_T_co | _S]: ...
    def transient(self) -> tset[_T_co]: ...
    def copy(self) -> Self: ...
    def clear(self) -> Self: ...
    def add(self, obj: _S, /) -> pset[_T_co | _S]: ...
    def addall(self, iterable: Iterable[_S]) -> pset[_T_co | _S]: ...
    def discard(self, obj: object, /) -> Self: ...
    def discardall(self, iterable: Iterable[object]) -> Self: ...
    def drop(self, obj: object, error: bool = False) -> Self: ...
    def remove(self, element: object) -> Self: ...
    def removeall(self, iterable: Iterable[object]) -> Self: ...
    def pop(self) -> tuple[_T_co, Self]: ...
    def union(self, *others: Iterable[_S]) -> pset[_T_co | _S]: ...
    def intersection(self, *others: Iterable[object]) -> Self: ...
    def difference(self, *others: Iterable[object]) -> Self: ...
    def symmetric_difference(self, *others: Iterable[_S]
                             ) -> pset[_T_co | _S]: ...
    def isdisjoint(self, other: Iterable[object]) -> bool: ...
    def issubset(self, other: Iterable[object]) -> bool: ...
    def issuperset(self, other: Iterable[object]) -> bool: ...


@disjoint_base
class tset(MutableSet[_T]):
    """A transient (mutable) set that can be efficiently converted to and
    from a `pset`."""
    __persistent_type__: ClassVar[type[pset[Any]]]
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @overload
    def __new__(cls) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T], /) -> Self: ...
    def __class_getitem__(cls, item: Any, /) -> Any: ...
    @classmethod
    def empty(cls) -> Self: ...
    def __contains__(self, obj: object, /) -> bool: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __len__(self) -> int: ...
    def __or__(self, other: Set[_S], /) -> tset[_T | _S]: ...
    def __ror__(self, other: Set[_S], /) -> tset[_T | _S]: ...  # type: ignore[misc]
    def __and__(self, other: Set[object], /) -> Self: ...
    def __sub__(self, other: Set[Any], /) -> Self: ...
    def __xor__(self, other: Set[_S], /) -> tset[_T | _S]: ...
    def add(self, obj: _T, /) -> None: ...
    def addall(self, iterable: Iterable[_T]) -> None: ...
    def discard(self, obj: object, /) -> None: ...
    def discardall(self, iterable: Iterable[object]) -> None: ...
    def removeall(self, iterable: Iterable[object]) -> None: ...
    def update(self, *others: Iterable[_T]) -> None: ...
    def difference_update(self, *others: Iterable[Any]) -> None: ...
    def intersection_update(self, *others: Iterable[Any]) -> None: ...
    def symmetric_difference_update(self, other: Iterable[_T]) -> None: ...
    def union(self, *others: Iterable[_S]) -> tset[_T | _S]: ...
    def intersection(self, *others: Iterable[object]) -> Self: ...
    def difference(self, *others: Iterable[object]) -> Self: ...
    def symmetric_difference(self, other: Iterable[_S]
                             ) -> tset[_T | _S]: ...
    def isdisjoint(self, other: Iterable[object]) -> bool: ...
    def issubset(self, other: Iterable[object]) -> bool: ...
    def issuperset(self, other: Iterable[object]) -> bool: ...
    def persistent(self) -> pset[_T]: ...
    def copy(self) -> Self: ...


#-------------------------------------------------------------------------------
# Lazy values

@disjoint_base
class lazy(Generic[_T_co]):
    """A value computed, at most once, by calling a function."""
    trace: ClassVar[bool]
    def __new__(cls, func: Callable[..., _T_co], /, *args: Any,
                **kwargs: Any) -> Self: ...
    def __call__(self) -> _T_co: ...
    def is_ready(self) -> bool: ...


class LazyError(RuntimeError):
    """The error raised when computing a `lazy` value fails."""
    @property
    def cause(self) -> BaseException | None: ...
    func: Callable[..., Any] | None
    func_args: tuple[Any, ...] | None
    func_kwargs: dict[str, Any] | None
    origin: tuple[str, int, str] | None
    origin_stack: list[str] | None


class _LazyErrorUnwrap:
    @overload
    def __call__(self, err: LazyError, /) -> BaseException: ...
    @overload
    def __call__(self, err: _T, /) -> _T: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None,
                 exc: BaseException | None,
                 tb: TracebackType | None, /) -> bool | None: ...

lazy_error_unwrap: _LazyErrorUnwrap


@overload
def unlazy(obj: lazy[_T], /) -> _T: ...
@overload
def unlazy(obj: _T, /) -> _T: ...


@overload
def holdlazy(obj: ldict[_K, _V], require_lazy: bool = False
             ) -> pdict[_K, _V | lazy[_V]]: ...
@overload
def holdlazy(obj: tldict[_K, _V], require_lazy: bool = False
             ) -> tdict[_K, _V | lazy[_V]]: ...
@overload
def holdlazy(obj: llist[_T], require_lazy: bool = False
             ) -> plist[_T | lazy[_T]]: ...
@overload
def holdlazy(obj: tllist[_T], require_lazy: bool = False
             ) -> tlist[_T | lazy[_T]]: ...
@overload
def holdlazy(obj: _T, require_lazy: Literal[False] = False) -> _T: ...


#-------------------------------------------------------------------------------
# Lazy collections
#
# The values of the lazy collections may be `lazy` objects; reading a value
# computes it, so the collections are typed by the computed values.

class ldict(pdict[_K, _V]):
    """A persistent dictionary whose `lazy` values are computed when read."""
    @overload
    def __new__(cls) -> Self: ...  # pyright: ignore[reportOverlappingOverload]
    @overload
    def __new__(cls, **kwargs: _V | lazy[_V]) -> ldict[str, _V]: ...
    @overload
    def __new__(cls, map: Mapping[_K, _V | lazy[_V]], /) -> Self: ...
    @overload
    def __new__(cls, map: Mapping[str, _V | lazy[_V]],
                /, **kwargs: _V | lazy[_V]) -> ldict[str, _V]: ...
    @overload
    def __new__(cls, iterable: Iterable[tuple[_K, _V | lazy[_V]]], /
                ) -> Self: ...
    def set(self, key: _K, val: _V | lazy[_V], /) -> Self: ...
    def transient(self) -> tldict[_K, _V]: ...
    @overload
    def getlazy(self, key: _K, default: None = None, /
                ) -> _V | lazy[_V] | None: ...
    @overload
    def getlazy(self, key: _K, default: _T, /) -> _V | lazy[_V] | _T: ...
    def is_lazy(self, key: _K, /) -> bool: ...
    def is_ready(self, key: _K, /) -> bool: ...
    def ready_all(self) -> Self: ...
    def held_pdict(self) -> pdict[_K, _V | lazy[_V]]: ...


class tldict(tdict[_K, _V]):
    """A transient dictionary whose `lazy` values are computed when read."""
    @overload
    def __new__(cls) -> Self: ...  # pyright: ignore[reportOverlappingOverload]
    @overload
    def __new__(cls, **kwargs: _V | lazy[_V]) -> tldict[str, _V]: ...
    @overload
    def __new__(cls, map: Mapping[_K, _V | lazy[_V]], /) -> Self: ...
    @overload
    def __new__(cls, map: Mapping[str, _V | lazy[_V]],
                /, **kwargs: _V | lazy[_V]) -> tldict[str, _V]: ...
    @overload
    def __new__(cls, iterable: Iterable[tuple[_K, _V | lazy[_V]]], /
                ) -> Self: ...
    def __setitem__(self, key: _K, value: _V | lazy[_V], /) -> None: ...
    def persistent(self) -> ldict[_K, _V]: ...
    @overload
    def getlazy(self, key: _K, default: None = None, /
                ) -> _V | lazy[_V] | None: ...
    @overload
    def getlazy(self, key: _K, default: _T, /) -> _V | lazy[_V] | _T: ...
    def is_lazy(self, key: _K, /) -> bool: ...
    def is_ready(self, key: _K, /) -> bool: ...
    def ready_all(self) -> Self: ...
    def held_tdict(self) -> tdict[_K, _V | lazy[_V]]: ...


class llist(plist[_T]):
    """A persistent list whose `lazy` elements are computed when read."""
    @overload
    def __new__(cls) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T | lazy[_T]], /) -> Self: ...
    def set(self, index: SupportsIndex, obj: _T | lazy[_T], /) -> Self: ...
    def append(self, obj: _T | lazy[_T], /) -> Self: ...
    def prepend(self, obj: _T | lazy[_T], /) -> Self: ...
    def transient(self) -> tllist[_T]: ...
    def getlazy(self, index: SupportsIndex, /) -> _T | lazy[_T]: ...
    def is_lazy(self, index: SupportsIndex, /) -> bool: ...
    def is_ready(self, index: SupportsIndex, /) -> bool: ...
    def ready_all(self) -> Self: ...
    def held_plist(self) -> plist[_T | lazy[_T]]: ...


class tllist(tlist[_T]):
    """A transient list whose `lazy` elements are computed when read."""
    @overload
    def __new__(cls) -> Self: ...
    @overload
    def __new__(cls, iterable: Iterable[_T | lazy[_T]], /) -> Self: ...
    def append(self, obj: _T | lazy[_T], /) -> None: ...
    def prepend(self, obj: _T | lazy[_T], /) -> None: ...
    def persistent(self) -> llist[_T]: ...
    def getlazy(self, index: SupportsIndex, /) -> _T | lazy[_T]: ...
    def is_lazy(self, index: SupportsIndex, /) -> bool: ...
    def is_ready(self, index: SupportsIndex, /) -> bool: ...
    def ready_all(self) -> Self: ...
    def held_tlist(self) -> tlist[_T | lazy[_T]]: ...


__all__ = (
    "plist", "tlist",
    "pset", "tset",
    "pdict", "tdict",
    "llist", "tllist",
    "ldict", "tldict",
    "lazy", "unlazy", "holdlazy",
    "LazyError", "lazy_error_unwrap")
