################################################################################
# tests.yml
# GitHub Actions Workflow for running the tests for the pcollections library.
# by Noah C. Benson

name: CI

# We run on either pushes or pulls into main or dev branches
on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '/.github/workflows/deploy.yml'
  pull_request:
    branches: [ main, dev ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '/.github/workflows/deploy.yml'
  # We sometimes want to run this manually.
  workflow_dispatch:
  # We also sometimes want to run this from another workflow.
  workflow_call:

# Our only job in this case is to test the code.
jobs:
  test:
    name: ${{matrix.version}}/${{matrix.os}}/${{matrix.arch}} - ${{github.event_name}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        os:
          - linux-latest
          - windows-latest
          - macos-13
        arch:
          - 'x64'
        include:
          - {"os": "macos-latest", "arch": "arm64", "version": "3.8"}
          - {"os": "macos-latest", "arch": "arm64", "version": "3.9"}
          - {"os": "macos-latest", "arch": "arm64", "version": "3.10"}
          - {"os": "macos-latest", "arch": "arm64", "version": "3.11"}
          - {"os": "macos-latest", "arch": "arm64", "version": "3.12"}
          - {"os": "macos-latest", "arch": "arm64", "version": "3.13"}
    # The job environment.
    env:
      OS: ${{ matrix.os }}
      ARCH: ${{ matrix.arch }}
      PYTHON: ${{ matrix.version }}
    # The steps in the job.
    steps:
      # Check out the repository (goes to $GITHUB_WORKSPACE)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '2'
      # Setup the Python Environment.
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
          architecture: ${{ matrix.arch }}
      - name: Upgrade Setuptools
        run: |
          python -m pip install --upgrade setuptools
      # Log the Python Version
      - name: Display Python version
        run: python --version
      # Run the actual tests.
      - name: Run Tests
        run: |
          pip install -e .
          #pip install coverage
          cd ~
          #coverage run -m pcollections.test
          python -m pcollections.test
#      - name: Process Code Coverage
#        uses: codecov/codecov-action@v1
